# Generated by Django 4.0.6 on 2022-07-20 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='carbay',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name', 'plate']},
        ),
    ]
